controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    joints:
      - front_left_hip_joint
      - front_left_thigh_joint
      - front_left_shin_joint
      - front_right_hip_joint
      - front_right_thigh_joint
      - front_right_shin_joint
      - rear_left_hip_joint
      - rear_left_thigh_joint
      - rear_left_shin_joint
      - rear_right_hip_joint
      - rear_right_thigh_joint
      - rear_right_shin_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      front_left_hip_joint: {p: 40.0, i: 0.0, d: 2.5}
      front_left_thigh_joint: {p: 40.0, i: 0.0, d: 2.5}
      front_left_shin_joint: {p: 40.0, i: 0.0, d: 2.5}
      
      front_right_hip_joint: {p: 40.0, i: 0.0, d: 2.5}
      front_right_thigh_joint: {p: 40.0, i: 0.0, d: 2.5}
      front_right_shin_joint: {p: 40.0, i: 0.0, d: 2.5}
      
      rear_left_hip_joint: {p: 40.0, i: 0.0, d: 2.5}
      rear_left_thigh_joint: {p: 40.0, i: 0.0, d: 2.5}
      rear_left_shin_joint: {p: 40.0, i: 0.0, d: 2.5}
      
      rear_right_hip_joint: {p: 40.0, i: 0.0, d: 2.5}
      rear_right_thigh_joint: {p: 40.0, i: 0.0, d: 2.5}
      rear_right_shin_joint: {p: 40.0, i: 0.0, d: 2.5}