controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_controller:
      type: dog_controllers/DogLegController

leg_controller:
  ros__parameters:
    joints:
      - front_left_hip_joint
      - front_left_knee_joint
      - front_right_hip_joint
      - front_right_knee_joint
      - rear_left_hip_joint
      - rear_left_knee_joint
      - rear_right_hip_joint
      - rear_right_knee_joint
    gait: trot
    step_length: 0.08
    step_height: 0.04
