controller_manager:
  ros__parameters:
    update_rate: 100
    robot_description: 'robot_description'
    hardware_plugin: "gazebo_ros2_control/GazeboSystem"
    joints:
      - front_left_hip
      - front_left_shin
      - front_left_thigh
      - front_right_hip
      - front_right_shin
      - front_right_thigh
      - rear_left_hip
      - rear_left_shin
      - rear_left_thigh
      - rear_right_hip
      - rear_right_shin
      - rear_right_thigh
